conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: channel_estimation
  quant_bit: 8
  pilot: 
    num: 16
    type: QPSK

  noise: 
    name: gaussian
    sigma: 0.05
